version: '3.4'

services:
  publisher_api:      
      build: ./publisher_api
      restart: always
        

  worker:
      
      build: ./worker
      restart: always
      depends_on:
        - "publisher_api"
        - "rabbitmq"

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    